# Generated by Django 4.0.1 on 2022-01-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_picture_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
