# Generated by Django 4.0.1 on 2022-01-28 05:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additionalInformation',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='<h1>No Additional Information</h1>', verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='<h1>No Description</h1>'),
        ),
    ]
