# Generated by Django 4.0.1 on 2022-01-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='These is no short description for this product', max_length=200),
        ),
    ]
