# Generated by Django 4.0.1 on 2022-01-31 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
