# Generated by Django 4.0.1 on 2022-02-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_faqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FAQs', to='product.product'),
        ),
    ]
